version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: playground
    ports:
      - 4000:80
    volumes:
      - .:/srv/web
      - .docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: pimplay
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: playground
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 4001:80
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
